version: "3.8"

services:
  webapi:
    image: nunenuh/fastapi-signoz-test:latest
    ports:
      - "8082:8081"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
