# Use Python 3.11 slim as base image
FROM python:3.11-slim


# Set environment variables
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    DEBIAN_FRONTEND=noninteractive \
    POETRY_VERSION=1.7.1 \
    POETRY_HOME="/opt/poetry" \
    POETRY_VIRTUALENVS_IN_PROJECT=true \
    POETRY_NO_INTERACTION=1 \
    PYTHONPATH=/app

# Add Poetry to PATH
ENV PATH="$POETRY_HOME/bin:$PATH"

# Install system dependencies including Tesseract and Poppler
RUN apt-get update && apt-get install -y --no-install-recommends \
    wget \
    curl \
    build-essential \
    tesseract-ocr \
    poppler-utils \
    curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    # Install Poetry
    && curl -sSL https://install.python-poetry.org | python3 -

# Create and set working directory
WORKDIR /app

# Copy only dependency files first
COPY poetry.lock pyproject.toml ./

# Copy project files
COPY src/ ./src/
COPY README.md ./README.md

# Install dependencies
RUN poetry install --only main && \
    poetry run pip install -e . && \
    rm -rf ~/.cache/pypoetry

# Create necessary directories and set permissions
RUN mkdir -p data && \
    chmod -R 755 /app && \
    useradd -m -u 1000 fsig && \
    chown -R fsig:fsig /app

# Switch to non-root user
USER fsig

# Command to run the FastAPI application with uvicorn
ENTRYPOINT ["poetry", "run", "uvicorn", "fastapi_signoz_test.main:app", "--host", "0.0.0.0", "--port", "8081"]
